import { Toaster } from 'sonner'
import '../globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Toaster />
      <body>{children}</body>
    </html>
  )
}
