import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
import Layout from "@/components/custom/Layout/Layout";
import AuthProvider from "@/context";
import { redirect } from "next/navigation";

const karla = Karla({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "TNV",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <main className="w-full">
              <Toaster />
              <Layout>
                {children}
              </Layout>
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
